- src/main/java/org/programmers/signalbuddyfinal/global/constant/ResponseStatus.java
- src/main/java/org/programmers/signalbuddyfinal/global/response/ApiResponse.java
- `ApiResponse` 추가 #12 
> 공통 Response 클래스 추가
> [Feat] 공통 Response 클래스 추가

- jenkins/develop.jenkinsfile
- src/main/java/org/programmers/signalbuddyfinal/domain/comment/controller/CommentController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/comment/dto/CommentRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/comment/entity/Comment.java
- src/main/java/org/programmers/signalbuddyfinal/domain/comment/repository/CommentRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/comment/repository/CustomCommentRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/comment/repository/CustomCommentRepositoryImpl.java
- src/main/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/entity/Member.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
- src/test/java/org/programmers/signalbuddyfinal/domain/comment/controller/CommentControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/comment/repository/CommentRepositoryTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
- src/test/java/org/programmers/signalbuddyfinal/global/support/RestDocsFormatGenerators.java
- #27 
> 피드백에 대한 댓글 기능을 구현했습니다.
> Jenkins 파일을 develop 브랜치를 대상으로 수정했습니다.
>
> [Feature] 피드백 댓글 기능

- .github/workflows/pr-ci.yaml
- build.gradle
- #31 
> SonarCloud에서 JaCoCo 결과를 보여주도록 한다.
>
> [Feature] SonarCloud JaCoCo 연동

- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/dto/FeedbackResponse.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepositoryImplTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
- #16 
> 사용자가 작성한 피드백 목록 조회 기능 구현
>
> [Feature] 자신이 쓴 글 목록 조회 기능 추가

- src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/exception/BookmarkErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/domain/comment/exception/CommentErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/exception/FeedbackErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/domain/like/exception/LikeErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/exception/MemberErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/domain/recentpath/exception/RecentPathErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/global/exception/ErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/global/exception/GlobalErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/global/exception/advice/GlobalExceptionHandler.java
- src/main/java/org/programmers/signalbuddyfinal/global/exception/advice/dto/ErrorResponse.java
- #38 
> `int code` -> `String code`로 변경
> [Refactor] ErrorCode 수정 사항 반영

- .github/workflows/docker-build.yaml
- jenkins/develop.jenkinsfile
- #41 
> github actions로 도커 이미지를 생성하고, 젠킨스 서버는 ssh로 배포를 하는 역할만 한다.
>
> [Fix] 젠킨스 서버 부하 줄이기

- .github/workflows/docker-build.yaml
- jenkins/develop.jenkinsfile
- #41 
> github actions로 도커 이미지를 생성하고, 젠킨스 서버는 ssh로 배포를 하는 역할만 한다.
>
> [Fix] jenkins 서버 과부하2

- .github/workflows/docker-build.yaml
- jenkins/develop.jenkinsfile
- #41 
> github actions로 도커 이미지를 생성하고, 젠킨스 서버는 ssh로 배포를 하는 역할만 한다.
>
> [Fix] jenkins 서버 과부하3

- .github/workflows/docker-build.yaml
- jenkins/develop.jenkinsfile
- #41 
> github actions로 도커 이미지를 생성하고, 젠킨스 서버는 ssh로 배포를 하는 역할만 한다.
>
> [Fix] jenkins 서버 과부하4

- .github/workflows/docker-build.yaml
- build.gradle
- jenkins/develop.jenkinsfile
- #41 
> github action에서 webhook 발생이 안 되는 문제를, 400초를 기다리고 배포하게 설정했습니다.
>
> [Fix] jenkins webhook 문제 해결

- src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberJoinRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/exception/MemberErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/repository/MemberRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
- #52 
> @RequestBody의 요청을 @RequestPart로 변경했습니다.
> 닉네임 중복검사를 추가했습니다.
> 프로필 이미지를 선택 사항으로 수정했습니다
>
> [Feature] 기본 회원가입 기능 구현

- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
- src/main/java/org/programmers/signalbuddyfinal/global/service/AwsFileService.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
- src/test/java/org/programmers/signalbuddyfinal/global/service/AwsFileServiceTest.java
- 향후 확장성 고려한 디렉토리 구조 변경
- #48 
> 향후 확장성을 고려한 S3 디렉토리 구조 변경
> [Refactor] S3 디렉토리 구조 변경

- build.gradle
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/dto/LoginRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/RedisConfig.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/CustomAuthenticationProvider.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/basic/CustomUserDetailsService.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/exception/CustomAuthenticationEntryPoint.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtService.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtUtil.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/RefreshToken.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/RefreshTokenRepository.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/TokenErrorCode.java
- src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/global/config/RedisConfig.java
- #58 
> cors setAllowedOrigins 수정
>소나큐브 피드백 반영하여 deprecated된 메서드 교체
> 로그인 시, 관리자 응답 에러로 나오던 것을 정상적인 에러 응답 하도록 수정
> JWT 관련 응답도 마찬가지로 수정하였습니다.
> 감사합니다.
>
> [Refactor] 토큰 관련 리팩터링

- src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
- #64 
> 사용자 프로필 이미지 변경 HTTP 메서드 `PATCH` -> `POST`
> [Refactor] 프로필 이미지 http 메서드 변경

- src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
- #73 
> 로그인 성공 후, 응답 값을 수정했습니다. 
>
> [Refactor] 로그인 성공 후 응답 수정

- src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
- S3 주소가 리턴되게 설정
- #71 
> 프로필 이미지 변경 리턴 데이터 수정
> [Fix] 프로필 이미지 변경 리턴 데이터 수정

- src/main/java/org/programmers/signalbuddyfinal/domain/auth/dto/EmailRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
- #81 
> 쿠키 및 헤더 설정을 변경했습니다.
>
> [Fix] 쿠키 설정 변경

- build.gradle
- src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
- #84 
> 말씀해주신 부분에 관한 CORS 설정 수정했습니다!
>
> [Fix] cors관련 설정 수정

- src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/repository/BookmarkRepositoryCustomImpl.java
- src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/service/MemberServiceTest.java
- #88 
> 북마크 삭제 로직 성능 개선
> 회원정보 수정 시 이메일, 닉네임 중복검사 추가
> [Refactor] 코드 리뷰 피드백

- src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
- 회원 프로필 이미지 변경 시 리턴 데이터 병합 오류 수정
- #78 
> 병합 수행 작업하면서 코드가 이전 코드로 바뀌어서 다시 작업하고 올렸습니다.
> [Fix] 잘못 병합된 코드 수정

- build.gradle
- src/main/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminFeedbackController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/controller/FeedbackController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/CustomFeedbackRepositoryImpl.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/controller/FeedbackReportController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/dto/FeedbackReportSearchRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/repository/CustomFeedbackReportRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/repository/CustomFeedbackReportRepositoryImpl.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback_report/service/FeedbackReportService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/feedback_summary/repository/CustomFeedbackSummaryRepositoryImpl.java
- src/main/java/org/programmers/signalbuddyfinal/global/constant/SearchTarget.java
- src/main/java/org/programmers/signalbuddyfinal/global/constant/SearchTargetConverter.java
- src/main/java/org/programmers/signalbuddyfinal/global/util/QueryDSLUtil.java
- src/main/java/org/programmers/signalbuddyfinal/global/util/QueryDslUtils.java
- src/test/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminFeedbackControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminFeedbackServiceTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback/controller/FeedbackControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback/repository/FeedbackRepositoryImplTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback/service/FeedbackServiceTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback_report/controller/FeedbackReportControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback_report/repository/FeedbackReportRepositoryTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback_summary/repository/CustomFeedbackSummaryRepositoryImplTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/feedback_summary/service/FeedbackSummaryServiceTest.java
- #77 
> 검색하는 API에 검색 범위를 설정할 수 있게 추가했습니다.
> 검색 범위는 `내용(+제목)`, `작성자` 중 하나를 정할 수 있습니다.
> Full Text Search를 QueryDSL로 사용하신다면  `QueryDslUtils` 클래스의 `fulltextSearch` 메서드를 사용해주세요!
>
> [Feature] 피드백 검색 조건 추가

- build.gradle
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/dto/VerifyCodeRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/entity/Purpose.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/exception/AuthErrorCode.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/EmailService.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/EmailConfig.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/exception/CustomAuthenticationEntryPoint.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtUtil.java
- src/main/resources/templates/member/mail.html
- src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
- #18 
> 이메일 인증 기능 구현했습니다.
> 인증 코드 유효 시간은 **3분**입니다.
> 비밀번호 재설정 및 계정복구 요청을 하기 위한 인증 유효 시간은 **10분**입니다.
> 현재는 인증된 사용자에 대해 저장할 때 key: email, value: "authenticated"로 되어있는데, 
> value로 더 좋은 값이 있다면 말씀주세요🤗🤗
> [Feature] 이메일 인증코드 전송 및 인증 기능 구현

- src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/dto/SocialLoginRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/repository/MemberRepository.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/CustomAuthenticationProvider.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
- src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
- #72 
> 소셜 로그인 기능 구현했습니다.
> 프론트에서 인증을 마치고 얻은 provider와 사용자의 uuid를 전달받아 
> DB에서 조회하고, 해당 사용자가 있으면 accessToken과 refreshToken을 생성합니다.
>
> [Feature] 소셜 로그인 기능 구현

- build.gradle
- src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
- #101
> swagger 페이지에서 openapi3.yaml 파일을 다운 받을 수 잇게 설정했습니다.
> 해당 파일 다운 받는 방법은 아래 스크린샷 참고 부탁드립니다!
>
> [Feature] openapi3yaml 파일 다운로드

- src/main/java/org/programmers/signalbuddyfinal/domain/bookmark/service/BookmarkService.java
- #114 
> 북마크 시퀀스 변경이 기대대로 이루어지지 않아 로직 수정.
>
> [Refactor] 시퀀스 변경 로직 수정

- src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/dto/MemberRestoreRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/entity/Member.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/postit_report/entity/PostItReport.java
- src/main/java/org/programmers/signalbuddyfinal/domain/postitsolve/entity/PostitSolve.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
- src/test/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberControllerTest.java
- #108 
> 이메일 인증이 완료된 사용자만 계정 복구를 진행할 수 있도록 작성했습니다.
>
> [Feature] 계정 복구 기능 구현

- src/main/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/admin/dto/AdminJoinRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/admin/service/AdminService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/controller/MemberController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
- src/test/java/org/programmers/signalbuddyfinal/domain/admin/controller/AdminControllerTest.java
- #122 
> 관리자 회원가입 시 닉네임 입력 추가, 프로필 이미지 입력 추가했습니다.
>
> [Feature] 관리자 회원가입 기능 추가

- src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/member/service/MemberService.java
- src/main/java/org/programmers/signalbuddyfinal/global/config/SecurityConfig.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/filter/JwtAuthorizationFilter.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtService.java
- src/main/java/org/programmers/signalbuddyfinal/global/security/jwt/JwtUtil.java
- src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
- #118 
> 새로운 액세스 토큰과 리프레시 토큰 발급하는경우, 기존의 액세스 토큰이 만료되지 않았다면 블랙리스트로 처리하고, 발급할 수 있도록 작성했습니다.
> 회원가입 할 때, 탈퇴한 사용자에 대한 예외를 추가했습니다.  
>
> [Refactor] reissue액세스토큰 검증 추가

- src/main/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentService.java
- src/main/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmService.java
- src/test/java/org/programmers/signalbuddyfinal/domain/comment/service/CommentServiceTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmServiceTest.java
- #134
> 피드백 작성자 제외한 다른 사용자가 댓글 작성 시, 작성자에게 댓글 알림을 보낸다.
> 댓글 작성 시, 알림 확인 테스트는 민혁님과 직접 테스트를 진행했습니다!
> [Feature] 피드백 댓글 알림 기능

- src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/dto/NavigationRequest.java
- src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/MapWebSocketHandler.java
- src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/NavigationWebSocketHandler.java
- src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CrossroadRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CustomCrossroadRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/repository/CustomCrossroadRepositoryImpl.java
- src/main/java/org/programmers/signalbuddyfinal/domain/crossroad/service/CrossroadService.java
- src/test/java/org/programmers/signalbuddyfinal/domain/crossroad/handler/NavigationWebSocketHandlerTest.java
- #137 
> `NavigationRequest` 수정
> `crossroadApiId` -> 위경도 값으로 변경
> [Refactor] 길찾기 기능 요청 값 변경

- src/main/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/auth/service/AuthService.java
- src/test/java/org/programmers/signalbuddyfinal/domain/auth/controller/AuthControllerTest.java
- #136
> 로그인 실패 시, 응답 값을 수정했습니다.
> `변경 전`
> ![image](https://github.com/user-attachments/assets/236c0069-f5d9-4b1d-bab1-f7a2b864cacf)
> `변경 후`
> ![image](https://github.com/user-attachments/assets/b694c529-4ea0-44b6-99eb-33c9195f2089)
>
> [Refactor] 로그인 실패 시, 응답값 변경

- jenkins/develop.jenkinsfile
- src/main/java/org/programmers/signalbuddyfinal/domain/notification/controller/FcmController.java
- src/main/java/org/programmers/signalbuddyfinal/domain/notification/entity/FcmToken.java
- src/main/java/org/programmers/signalbuddyfinal/domain/notification/repository/FcmTokenRepository.java
- src/main/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmService.java
- src/test/java/org/programmers/signalbuddyfinal/domain/notification/controller/FcmControllerTest.java
- src/test/java/org/programmers/signalbuddyfinal/domain/notification/service/FcmServiceTest.java
- #141 
> FCM 디바이스 토큰을 한 계정에서 여러 개 등록 가능하게 했습니다.
> 멀티캐스트 전송은 민혁님과 직접 테스트 해보았고 정상적으로 이루어지는 것을 확인했습니다.
> [Feature] 알림 사용자 기기 복수 등록
